services:
  tinder:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start:dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/usr/src/app/src
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/postgres:/var/lib/postgresql/data1
    env_file:
      - .env   